// <auto-generated />
using System;
using ASPNetCoreApplicationPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNetCoreApplicationPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190921080314_CorrectPhotoPath")]
    partial class CorrectPhotoPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNetCoreApplicationPractice.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<int>("Department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhotoPath");

                    b.Property<long?>("Salary")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "India1",
                            Department = 6,
                            Name = "Alok1 Gautam",
                            Salary = 1200000L
                        },
                        new
                        {
                            Id = 2,
                            Address = "India2",
                            Department = 5,
                            Name = "Alok2 Gautam",
                            Salary = 2200000L
                        },
                        new
                        {
                            Id = 3,
                            Address = "India3",
                            Department = 2,
                            Name = "Alok3 Gautam",
                            Salary = 3200000L
                        },
                        new
                        {
                            Id = 4,
                            Address = "India4",
                            Department = 1,
                            Name = "Alok4 Gautam",
                            Salary = 4200000L
                        },
                        new
                        {
                            Id = 5,
                            Address = "India5",
                            Department = 3,
                            Name = "Alok5 Gautam",
                            Salary = 5200000L
                        },
                        new
                        {
                            Id = 6,
                            Address = "India6",
                            Department = 4,
                            Name = "Alok6 Gautam",
                            Salary = 6200000L
                        },
                        new
                        {
                            Id = 7,
                            Address = "India7",
                            Department = 7,
                            Name = "Alok7 Gautam",
                            Salary = 7200000L
                        },
                        new
                        {
                            Id = 8,
                            Address = "India8",
                            Department = 0,
                            Name = "Alok8 Gautam",
                            Salary = 7200000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
